export const ALLOWED_COMPANIES = [
  'Pfizer',
  'Johnson & Johnson',
  'Sinopharm',
  'Roche',
  'Merck & Co.',
  'AbbVie',
  'Bayer',
  'Novartis',
  'Sanofi',
  'Bristol Myers Squibb',
  'AstraZeneca',
  'Abbott Laboratories',
  'GSK',
  'Takeda',
  'Eli Lilly',
  'Gilead Sciences',
  'Amgen',
  'Boehringer Ingelheim',
  'Novo Nordisk',
  'Merck Group',
  'Siemens Healthcare',
  'Moderna',
  'BioNTech',
  'Jointown Pharmaceuticals',
  'GE Healthcare',
  'Viatris',
  'Baxter International',
  'Teva Pharmaceuticals',
  'Haleon',
  'Cipla',
  'Aurobindo',
  'Alembic',
  'Lupin',
  'Glenmark',
  'Sun Pharma',
  'Biological E',
  'Sandoz',
  'Hetero',
  'Mylan',
  'Biophore',
  'Biocon',
  'Torrent',
  "Dr. Reddy's",
  "Divi's",
  'Mankind',
  'Gland Pharma',
  'Intas',
  'Bharat Biotech',
  'Emcure',
  'Piramal',
  'Alkem',
  'Laurus Labs',
  'Bal Pharma',
  'Par Pharma',
  'Ferring Pharmaceuticals',
  'Jamp Pharma',
  'Ipca',
  'Natco',
  'Accenture',
  'TCS',
  'Wipro',
  'Cognizant',
];

export function isCompanyAllowed(company: string): boolean {
  const normalizedCompany = company.toLowerCase().trim();
  return ALLOWED_COMPANIES.some(
    (allowed) => allowed.toLowerCase().trim() === normalizedCompany
  );
}
