/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobSource = IDL.Variant({
  'linkedin' : IDL.Null,
  'other' : IDL.Null,
  'indeed' : IDL.Null,
  'workday' : IDL.Null,
  'companySite' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredLocations' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'source' : JobSource,
  'postedTime' : Time,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobSource],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllJobsIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [Job], ['query']),
  'getSavedJobIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveJob' : IDL.Func([IDL.Nat], [], []),
  'searchJobs' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'shouldIncludeJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobSource = IDL.Variant({
    'linkedin' : IDL.Null,
    'other' : IDL.Null,
    'indeed' : IDL.Null,
    'workday' : IDL.Null,
    'companySite' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredLocations' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'source' : JobSource,
    'postedTime' : Time,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobSource],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllJobsIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [Job], ['query']),
    'getSavedJobIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveJob' : IDL.Func([IDL.Nat], [], []),
    'searchJobs' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'shouldIncludeJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };