/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Job {
  'id' : bigint,
  'title' : string,
  'source' : JobSource,
  'postedTime' : Time,
  'description' : string,
  'company' : string,
  'location' : string,
}
export type JobSource = { 'linkedin' : null } |
  { 'other' : null } |
  { 'indeed' : null } |
  { 'workday' : null } |
  { 'companySite' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'preferredLocations' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJob' : ActorMethod<[string, string, string, string, JobSource], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllJobsIds' : ActorMethod<[], Array<bigint>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[bigint], Job>,
  'getSavedJobIds' : ActorMethod<[], Array<bigint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveJob' : ActorMethod<[bigint], undefined>,
  'searchJobs' : ActorMethod<[string, string], Array<bigint>>,
  'shouldIncludeJob' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];